name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.kishlaykumar15 }}  # Your Docker Hub username
  IMAGE_NAME: hello-world-python                        # Your image name
  CUSTOM_TAG: "22f1001112"                             # Your custom tag

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build Docker image
      - name: Build image
        run: |
          docker build -t $kishlaykumar15/$IMAGE_NAME:latest .

      # 4. Tag with custom tag
      - name: Tag image
        run: |
          docker tag $DOCKERHUB_USERNAME/$IMAGE_NAME:latest $DOCKERHUB_USERNAME/$IMAGE_NAME:$CUSTOM_TAG

      # 5. Push both tags
      - name: Push images
        run: |
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$CUSTOM_TAG

      # (Optional) Debug step
      - name: Verify tags
        run: |
          docker images | grep $DOCKERHUB_USERNAME/$IMAGE_NAME
