name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.kishlaykumar15 }}
  IMAGE_NAME: hello-world-python
  CUSTOM_TAG: ${{ secrets.22f1001112 }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.kishlaykumar15 }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t $kishlaykumar15/$IMAGE_NAME:latest .

    - name: Tag image with custom tag
      run: |
        docker tag $kishlaykumar15/$IMAGE_NAME:latest $kishlaykumar15/$IMAGE_NAME:$22f1001112

    - name: Push latest tag
      run: |
        docker push $kishlaykumar15/$IMAGE_NAME:latest

    - name: Push custom tag
      run: |
        docker push $kishlaykumar15/$IMAGE_NAME:$22f1001112
